### ISSUE TITLE
Mail/Postal Address?

### ISSUE THREAD

**Issue by hboiled** [hboiled/AddressBook#7]
We could potentially add a column to the address model that designates it as a postal address.

**Comment by IsaacVallejo** [comment]
what do you mean by this?

**Comment by hboiled** [comment]
In the Address model, a prop 
public bool IsMailAddress { get; set; }

could be added so we can keep track of whether the address is also the person's mail address.  This could be added in the future. We should just get the simplest model working for now.

**Comment by IsaacVallejo** [comment]
okay. this will be done soon.

**Comment by hboiled** [comment]
This has been implemented
